#!/bin/sh

# @example
#   ./copy-dragonruby ~/Downloads/dragonruby-gtk-macos/dragonruby-macos .

# Set the source and destination directories
source_dir="$1"
destination_dir="$2"

# Check if source directory exists
if [ ! -d "$source_dir" ]; then
  echo "Error: Source directory '$source_dir' does not exist."
  exit 1
fi

if [ -z "$destination_dir" ]; then
  echo "No destination given."
  exit 1
fi

# Check if destination directory exists, create if it doesn't
if [ ! -d "$destination_dir" ]; then
  mkdir -p "$destination_dir"
  echo "Destination directory '$destination_dir' created."
fi

# Copy all directories from source to destination
find "$source_dir" -maxdepth 1 -print0 | while IFS= read -r -d $'\0' filename; do
    base_filename="$(basename "$filename")"

    # dont copy the inner directory.
    if [ "$source_dir" = "$filename" ]; then
      continue
    fi

    if [ "$base_filename" = "mygame" ] && [ -d "$destination_dir/mygame" ]; then
      # "mygame" already exists. Don't overwrite it.
      continue
    fi

    cp -R "$filename" .
    echo "Copying: "$base_filename" ..."
done

echo "All directories copied successfully."
